"""
Tests for Prometheus metrics endpoint in Signal Service.

Verifies that:
1. /metrics endpoint exists and returns Prometheus-formatted data
2. All defined metrics are present in the output
3. Metrics have correct initial values
4. Metric naming follows Prometheus conventions
"""

import pytest
from fastapi.testclient import TestClient


@pytest.fixture
def client():
    """Create test client for Signal Service."""
    # Import here to avoid issues with module-level initialization
    from apps.signal_service.main import app

    return TestClient(app)


class TestPrometheusMetrics:
    """Test suite for Prometheus metrics endpoint."""

    def test_metrics_endpoint_exists(self, client):
        """Test that /metrics endpoint exists and returns 200."""
        response = client.get("/metrics")
        assert response.status_code == 200

    def test_metrics_content_type(self, client):
        """Test that /metrics returns correct content type."""
        response = client.get("/metrics")
        # Prometheus exposition format
        assert "text/plain" in response.headers.get("content-type", "")

    def test_signal_requests_total_metric_exists(self, client):
        """Test that signal_service_requests_total metric exists."""
        response = client.get("/metrics")
        assert response.status_code == 200

        # Check metric name and help text
        assert "signal_service_requests_total" in response.text
        assert "Total number of signal generation requests" in response.text

    def test_signal_generation_duration_metric_exists(self, client):
        """Test that signal_service_signal_generation_duration_seconds metric exists."""
        response = client.get("/metrics")
        assert response.status_code == 200

        assert "signal_service_signal_generation_duration_seconds" in response.text
        assert "Time taken to generate signals" in response.text

    def test_signals_generated_total_metric_exists(self, client):
        """Test that signal_service_signals_generated_total metric exists."""
        response = client.get("/metrics")
        assert response.status_code == 200

        assert "signal_service_signals_generated_total" in response.text
        assert "Total number of signals generated by symbol" in response.text

    def test_model_predictions_total_metric_exists(self, client):
        """Test that signal_service_model_predictions_total metric exists."""
        response = client.get("/metrics")
        assert response.status_code == 200

        assert "signal_service_model_predictions_total" in response.text
        assert "Total number of model predictions made" in response.text

    def test_model_reload_total_metric_exists(self, client):
        """Test that signal_service_model_reload_total metric exists."""
        response = client.get("/metrics")
        assert response.status_code == 200

        assert "signal_service_model_reload_total" in response.text
        assert "Total number of model reload attempts" in response.text

    def test_database_connection_status_metric_exists(self, client):
        """Test that signal_service_database_connection_status metric exists."""
        response = client.get("/metrics")
        assert response.status_code == 200

        assert "signal_service_database_connection_status" in response.text
        assert "Database connection status" in response.text

    def test_redis_connection_status_metric_exists(self, client):
        """Test that signal_service_redis_connection_status metric exists."""
        response = client.get("/metrics")
        assert response.status_code == 200

        assert "signal_service_redis_connection_status" in response.text
        assert "Redis connection status" in response.text

    def test_model_loaded_status_metric_exists(self, client):
        """Test that signal_service_model_loaded_status metric exists."""
        response = client.get("/metrics")
        assert response.status_code == 200

        assert "signal_service_model_loaded_status" in response.text
        assert "Model loaded status" in response.text

    def test_model_version_info_metric_exists(self, client):
        """Test that signal_service_model_version metric exists."""
        response = client.get("/metrics")
        assert response.status_code == 200

        assert "signal_service_model_version" in response.text
        assert "Current model version information" in response.text

    def test_database_connection_status_initial_value(self, client):
        """Test that database_connection_status has initial value."""
        response = client.get("/metrics")
        assert response.status_code == 200

        # Should be set to 1 initially (assuming DB is up in tests)
        assert "signal_service_database_connection_status 1.0" in response.text

    def test_model_loaded_status_initial_value(self, client):
        """Test that model_loaded_status has initial value."""
        response = client.get("/metrics")
        assert response.status_code == 200

        # Should be set to 0 initially (model loads during lifespan)
        assert "signal_service_model_loaded_status 0.0" in response.text

    def test_all_required_metrics_present(self, client):
        """Test that all required metrics are present in output."""
        response = client.get("/metrics")
        assert response.status_code == 200

        required_metrics = [
            "signal_service_requests_total",
            "signal_service_signal_generation_duration_seconds",
            "signal_service_signals_generated_total",
            "signal_service_model_predictions_total",
            "signal_service_model_reload_total",
            "signal_service_database_connection_status",
            "signal_service_redis_connection_status",
            "signal_service_model_loaded_status",
            "signal_service_model_version",
        ]

        for metric in required_metrics:
            assert metric in response.text, f"Missing metric: {metric}"

    def test_metrics_naming_convention(self, client):
        """Test that all metrics follow Prometheus naming conventions."""
        response = client.get("/metrics")
        assert response.status_code == 200

        # All metrics should start with service name prefix
        lines = response.text.split("\n")
        metric_lines = [
            line
            for line in lines
            if not line.startswith("#") and line.strip() and "signal_service_" in line
        ]

        for line in metric_lines:
            # Each metric line should start with signal_service_
            assert (
                "signal_service_" in line
            ), f"Metric doesn't follow naming convention: {line}"

    def test_metrics_have_help_text(self, client):
        """Test that all metrics have HELP text."""
        response = client.get("/metrics")
        assert response.status_code == 200

        metrics = [
            "signal_service_requests_total",
            "signal_service_signal_generation_duration_seconds",
            "signal_service_signals_generated_total",
            "signal_service_model_predictions_total",
            "signal_service_model_reload_total",
            "signal_service_database_connection_status",
            "signal_service_redis_connection_status",
            "signal_service_model_loaded_status",
            "signal_service_model_version",
        ]

        for metric in metrics:
            # Check for HELP line
            assert f"# HELP {metric}" in response.text, f"Missing HELP text for: {metric}"

    def test_metrics_have_type_declaration(self, client):
        """Test that all metrics have TYPE declaration."""
        response = client.get("/metrics")
        assert response.status_code == 200

        metrics = [
            "signal_service_requests_total",
            "signal_service_signal_generation_duration_seconds",
            "signal_service_signals_generated_total",
            "signal_service_model_predictions_total",
            "signal_service_model_reload_total",
            "signal_service_database_connection_status",
            "signal_service_redis_connection_status",
            "signal_service_model_loaded_status",
        ]

        for metric in metrics:
            # Check for TYPE line
            assert f"# TYPE {metric}" in response.text, f"Missing TYPE declaration for: {metric}"

    def test_counter_metrics_have_total_suffix(self, client):
        """Test that counter metrics end with _total suffix."""
        response = client.get("/metrics")
        assert response.status_code == 200

        # Counter metrics should end with _total
        counter_metrics = [
            "signal_service_requests_total",
            "signal_service_signals_generated_total",
            "signal_service_model_predictions_total",
            "signal_service_model_reload_total",
        ]

        for metric in counter_metrics:
            assert metric.endswith("_total"), f"Counter metric missing _total suffix: {metric}"
            assert f"# TYPE {metric} counter" in response.text

    def test_histogram_metrics_have_correct_type(self, client):
        """Test that histogram metrics are declared correctly."""
        response = client.get("/metrics")
        assert response.status_code == 200

        histogram_metrics = ["signal_service_signal_generation_duration_seconds"]

        for metric in histogram_metrics:
            assert f"# TYPE {metric} histogram" in response.text

    def test_gauge_metrics_have_correct_type(self, client):
        """Test that gauge metrics are declared correctly."""
        response = client.get("/metrics")
        assert response.status_code == 200

        gauge_metrics = [
            "signal_service_database_connection_status",
            "signal_service_redis_connection_status",
            "signal_service_model_loaded_status",
        ]

        for metric in gauge_metrics:
            assert f"# TYPE {metric} gauge" in response.text

    def test_metrics_endpoint_performance(self, client):
        """Test that /metrics endpoint responds quickly."""
        import time

        start = time.time()
        response = client.get("/metrics")
        duration = time.time() - start

        assert response.status_code == 200
        # Metrics endpoint should respond in < 100ms
        assert duration < 0.1, f"Metrics endpoint too slow: {duration:.3f}s"
