-- Migration: Backfill trades from order metadata fills (P5T10)
--
-- Purpose:
-- Populate trades table from existing order metadata fills
-- (generated by Alpaca webhooks or reconciliation backfills).
--
-- Created: 2026-01-11
-- Author: Codex CLI

INSERT INTO trades (
  trade_id,
  client_order_id,
  broker_order_id,
  strategy_id,
  symbol,
  side,
  qty,
  price,
  executed_at,
  realized_pnl,
  source,
  synthetic,
  superseded,
  created_at
)
SELECT
  fill->>'fill_id' AS trade_id,
  o.client_order_id,
  o.broker_order_id,
  o.strategy_id,
  o.symbol,
  o.side,
  COALESCE(NULLIF(fill->>'fill_qty', '')::NUMERIC, 0) AS qty,
  COALESCE(NULLIF(fill->>'fill_price', '')::NUMERIC, 0) AS price,
  COALESCE(
    NULLIF(fill->>'timestamp', '')::timestamptz,
    o.filled_at,
    o.updated_at,
    o.created_at
  ) AS executed_at,
  COALESCE(NULLIF(fill->>'realized_pl', '')::NUMERIC, 0) AS realized_pnl,
  NULLIF(fill->>'source', '') AS source,
  COALESCE((fill->>'synthetic')::boolean, false) AS synthetic,
  COALESCE((fill->>'superseded')::boolean, false) AS superseded,
  NOW() AS created_at
FROM orders o
CROSS JOIN LATERAL jsonb_array_elements(COALESCE(o.metadata->'fills', '[]'::jsonb)) AS fill
WHERE fill->>'fill_id' IS NOT NULL
  AND fill->>'fill_id' <> ''
  -- Validate qty and price to satisfy CHECK constraints (qty > 0, price > 0)
  -- Fills with missing/invalid values are logged and skipped
  AND COALESCE(NULLIF(fill->>'fill_qty', '')::NUMERIC, 0) > 0
  AND COALESCE(NULLIF(fill->>'fill_price', '')::NUMERIC, 0) > 0
ON CONFLICT (trade_id) DO NOTHING;
